Added the BufferSize option to the AsyncAppender and updated UnitTestBoundedFIFO to test this new feature.
git-svn-id: https://svn.eu.apache.org/repos/asf/logging/log4j/trunk@308966 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/java/org/apache/log4j/test/unitTest b/src/java/org/apache/log4j/test/unitTest
--- a/src/java/org/apache/log4j/test/unitTest
+++ b/src/java/org/apache/log4j/test/unitTest
@@ -21,6 +21,12 @@ if [ $? != 0 ]; then
   exit 1   
 fi
 
+java junit.textui.TestRunner org.apache.log4j.test.UnitTestBoundedFIFO
+if [ $? != 0 ]; then
+  echo "UnitUnitTestBoundedFIFO failed."
+  exit 1   
+fi
+
 java junit.textui.TestRunner org.apache.log4j.test.UnitTestOR
 if [ $? != 0 ]; then
   echo "UnitTestOR failed."
