Slightly improved the ANT build file (build.xml).
Playing around with the JMSSink and object renderer of type MessageRenderer.java

More importantly, the RendererMap is now able to cope with renderer for interfaces
as well as non-interface classes. This change was mandated by the use of JMS where
most things are interfaces with concrete provider specific implementations underneath.


git-svn-id: https://svn.eu.apache.org/repos/asf/logging/log4j/trunk@308910 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/src/java/org/apache/log4j/test/unitTest b/src/java/org/apache/log4j/test/unitTest
--- a/src/java/org/apache/log4j/test/unitTest
+++ b/src/java/org/apache/log4j/test/unitTest
@@ -19,3 +19,9 @@ if [ $? != 0 ]; then
   echo "UnitTestCyclicBuffer failed."
   exit 1   
 fi
+
+java junit.textui.TestRunner org.apache.log4j.test.UnitTestOR
+if [ $? != 0 ]; then
+  echo "UnitTestOR failed."
+  exit 1   
+fi
